### ISSUE TITLE
Lambda zip upload paths

### ISSUE THREAD

**Issue by vaibhavranjith** [aws-samples/amazon-rds-auto-restart-protection#3]
Hello,
 
I would like to thank you, for this solution.

Here is a note that I would like to make about a discrepancy I noted while deploying the CloudFormation stack after reading the README.md file given.

```
StartStateMachineExecutionLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: s3Bucket
        S3Key: start-statemachine-execution-lambda.zip
      Description: Lambda function to start the Step Functions state machine execution
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          STEPFUNCTION_ARN:
            Ref: StopRdsInstanceStateMachine
      Role:
        Fn::GetAtt:
        - StartStateMachineExecutionLambdaRole
        - Arn
      Runtime: python3.7
      Tags:
      - Key: Project
        Value: RdsAutoRestartProtection
```
The s3 key just mentions to upload the lambda zip files at the root of the s3 bucket. While The README.md file asks me to upload the lambda zips and the step function code under the following prefixes.

> sources/lambda-deployment-packages
> sources/stepfunction-code
